services:
  - type: web
    name: siqa-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn servidor:app
    envVars:
      - key: DATABASE_URL
        sync: false
