
create extension if not exists pgcrypto;

create table if not exists public.ambientes (
  id uuid primary key default gen_random_uuid(),
  nome text not null unique,
  limite_co2 integer not null default 1000,
  ativo boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.leituras (
  id bigint generated by default as identity primary key,
  ambiente_id uuid not null references public.ambientes(id) on delete cascade,
  co2 numeric(10,2) not null check (co2 >= 0),
  temperatura numeric(5,2) not null,
  umidade numeric(5,2) not null check (umidade between 0 and 100),
  pm25 numeric(8,2),
  coletado_em timestamptz not null default now()
);

create table if not exists public.alertas (
  id bigint generated by default as identity primary key,
  ambiente_id uuid references public.ambientes(id) on delete set null,
  tipo text not null,
  texto text not null,
  severidade text not null default 'atencao' check (severidade in ('info','atencao','critico')),
  lido boolean not null default false,
  criado_em timestamptz not null default now()
);

create index if not exists idx_leituras_ambiente_data on public.leituras(ambiente_id, coletado_em desc);
create index if not exists idx_alertas_data on public.alertas(criado_em desc);

alter table public.ambientes enable row level security;
alter table public.leituras enable row level security;
alter table public.alertas enable row level security;

drop policy if exists "public read ambientes" on public.ambientes;
create policy "public read ambientes" on public.ambientes for select to anon using (true);

drop policy if exists "public read leituras" on public.leituras;
create policy "public read leituras" on public.leituras for select to anon using (true);

drop policy if exists "public insert leituras" on public.leituras;
create policy "public insert leituras" on public.leituras for insert to anon with check (true);

drop policy if exists "public read alertas" on public.alertas;
create policy "public read alertas" on public.alertas for select to anon using (true);

drop policy if exists "public insert alertas" on public.alertas;
create policy "public insert alertas" on public.alertas for insert to anon with check (true);

-- Dados iniciais
insert into public.ambientes (nome, limite_co2) values
('Sala 01',1000),('Sala 02',1000),('Sala 03',1000),('Sala 04',1000)
on conflict (nome) do nothing;

insert into public.leituras (ambiente_id,co2,temperatura,umidade,pm25,coletado_em)
select id, 620,22.1,52,12,now()-interval '5 hours' from public.ambientes where nome='Sala 01';
insert into public.leituras (ambiente_id,co2,temperatura,umidade,pm25,coletado_em)
select id, 980,24.8,59,16,now()-interval '1 hour' from public.ambientes where nome='Sala 02';
insert into public.leituras (ambiente_id,co2,temperatura,umidade,pm25,coletado_em)
select id, 710,23.0,54,10,now()-interval '3 hours' from public.ambientes where nome='Sala 03';
insert into public.leituras (ambiente_id,co2,temperatura,umidade,pm25,coletado_em)
select id, 680,22.9,53,9,now()-interval '2 hours' from public.ambientes where nome='Sala 04';


